### ISSUE TITLE
环境都配置好了，但是运行的时候有AttributeError: 'YamlParser' object has no attribute 'DEEPSORT'错误，请问是怎么回事啊？

### ISSUE THREAD

**Issue by menglongsl** [owo12321/Yolov5_DeepSort_Traffic-counter#17]
60 25.0 1280.0 720.0
Traceback (most recent call last):
  File "count.py", line 457, in <module>
    detect(args)
  File "count.py", line 232, in detect
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
AttributeError: 'YamlParser' object has no attribute 'DEEPSORT'

**Comment by owo12321** [comment]
> 60 25.0 1280.0 720.0 Traceback (most recent call last): File "count.py", line 457, in detect(args) File "count.py", line 232, in detect deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT, AttributeError: 'YamlParser' object has no attribute 'DEEPSORT'

参考这两个：
https://blog.csdn.net/qq_26847897/article/details/123360426
https://blog.csdn.net/weixin_43446161/article/details/121079971

**Comment by menglongsl** [comment]
好的，多谢大佬，我已经改好了，是安装了最新的easydict就可以了
