### ISSUE TITLE
可以给我一份环境镜像文件吗

### ISSUE THREAD

**Issue by Nicloeccc** [owo12321/Yolov5_DeepSort_Traffic-counter#25]

**Comment by owo12321** [comment]
我在windows下跑的

**Comment by Nicloeccc** [comment]
> 我在windows下跑的

cuda10.2有安装包吗，官网的下不了

**Comment by Nicloeccc** [comment]
Could not find a version that satisfies the requirement torchvision==0.8.2，这个版本找不到有替代的吗

**Comment by owo12321** [comment]
https://download.pytorch.org/whl/torchvision/  
这是官方的下载地址，找你需要的版本

**Comment by owo12321** [comment]
https://pytorch.org/get-started/previous-versions/  
在这里看和pytorch的版本对应关系

**Comment by Nicloeccc** [comment]
ModuleAttributeError: 'Detect' object has no attribute 'm'
，为什么会报这个错

**Comment by Nicloeccc** [comment]
File "./yolov5\models\yolo.py", line 46, in forward
    x[i] = self.m[i](x[i])  # conv
  File "C:\Users\Li Hao\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'为什么会报这个错

**Comment by Nicloeccc** [comment]
是torch版本不对吗，我下的1.7.1

**Comment by owo12321** [comment]
是不是pt文件的版本没用对，用的应该是5.0版本的yolov5  
https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt

**Comment by Nicloeccc** [comment]
Traceback (most recent call last):
  File "count.py", line 448, in <module>
    detect(args)
  File "count.py", line 253, in detect
    pred = model(img, augment=opt.augment)[0]
  File "C:\Users\Li Hao\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./yolov5\models\yolo.py", line 117, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "./yolov5\models\yolo.py", line 148, in forward_once
    x = m(x)  # run
  File "C:\Users\Li Hao\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./yolov5\models\yolo.py", line 46, in forward
    x[i] = self.m[i](x[i])  # conv
  File "C:\Users\Li Hao\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

**Comment by owo12321** [comment]
https://blog.csdn.net/qq_44847636/article/details/113588405  
https://blog.csdn.net/Joseph__Lagrange/article/details/108255992  
参考这两篇博客，应该就是你的权重文件的版本没下对

**Comment by Nicloeccc** [comment]
能把pip list发我一份吗，num一直为0，torch版本一直不行，我是AMD64

**Comment by Nicloeccc** [comment]
如果我要改成多线程，使用多个摄像头，source_dir要怎么改

**Comment by owo12321** [comment]
没有实现这个功能

**Comment by Nicloeccc** [comment]
如果我想用两个摄像头，要怎么改这个主函数

**Comment by Nicloeccc** [comment]
怎么改成撞线检测，逐帧计数会有重复的

**Comment by owo12321** [comment]
我实现的就是啊  
计数方法是每一帧都计算框和线的位置关系，并和上一帧的位置做比较。如果某一帧框在线的一侧，下一帧跑到另一侧了，就说明跨线了，对应方向计数+1

**Comment by Nicloeccc** [comment]
运行中，终端打印的就是视频中检测的人数，左上角那两个dir的值就是撞线检测统计的？

**Comment by owo12321** [comment]
终端打印啥我忘了，两个dir就是对应颜色的线，沿从右往左和从左往右两个方向的跨线统计

**Comment by Nicloeccc** [comment]
为什么我在后面打印的line[6][0]数字不对

**Comment by Nicloeccc** [comment]
为什么我在后面打印line[6][0]的数据跟视频里显示的对不上，不能直接打印吗

**Comment by Nicloeccc** [comment]
我想得到line[6][0]和line[6][1]里面的数据该怎么做

**Comment by owo12321** [comment]
计算过程在330行这一块，但嵌套层级有点复杂，所以建议在380行画线和标注文字这块打印，亲测在这里打印与视频一致  
for line in lines:  
    print(line[6][0], line[6][1])

**Comment by owo12321** [comment]
这几天有些忙，没法及时回复，实在抱歉

**Comment by Nicloeccc** [comment]
我遍历打印line[6][0]，有两个数据只有上面那个数据与视频上是对应
![两个](https://github.com/owo12321/Yolov5_DeepSort_Traffic-counter/assets/102214692/2b403db2-29fc-496f-8e7f-ec8de1638ee9)
的

**Comment by Nicloeccc** [comment]
line[6][0]遍历打印出来有两个值，我想把这两个值单独存放进变量该怎么做

**Comment by owo12321** [comment]
我这里打印出来是正常的
![Uploading Snipaste_2024-04-17_10-16-49.jpg…]()

**Comment by owo12321** [comment]
![Snipaste_2024-04-17_10-16-49](https://github.com/owo12321/Yolov5_DeepSort_Traffic-counter/assets/58645453/d82454d8-3b98-405e-b628-f9cb7afde927)

**Comment by owo12321** [comment]
这里打印出来的四个数就是两条线两个方向各自的统计值

**Comment by Nicloeccc** [comment]
我知道是正常的，line[6][0]打印出来是两个方向的，我想单独取一个数写进数据库，但不知道如何单独读取出来

**Comment by owo12321** [comment]
line[6][0]只是一个方向的啊，line[6][1]是另一个方向

**Comment by owo12321** [comment]
for i in range(len(lines)):
    print(lines[i][6][0], lines[i][6][1])
这么写可能会更好理解一点？
lines里定义有多条线，每条线里边的的第6个元素是一个包含两个数的list，表示这条线两个跨线方向的计数值

**Comment by owo12321** [comment]
默认的测试用例有两条线的

**Comment by Nicloeccc** [comment]
我只想要一条线，一个方向的跨线统计，但是你的line[6][0]存放了两条线的跨线统计

**Comment by Nicloeccc** [comment]
我一直访问不了line[6][0]存放列表中的第一个数

**Comment by owo12321** [comment]
![Snipaste_2024-04-17_12-34-03](https://github.com/owo12321/Yolov5_DeepSort_Traffic-counter/assets/58645453/74f277e3-500e-4bbb-8efa-58dfc0c77544)
这里我只画了一条线，你看这个输出应该是你想要的吧
只有一条线的话就直接lines[0][6][0]，这是一个数，不是一个列表

**Comment by Nicloeccc** [comment]
你好，请问下，执行程序，没有视频窗口是怎么回事

**Comment by Nicloeccc** [comment]
![问题](https://github.com/owo12321/Yolov5_DeepSort_Traffic-counter/assets/102214692/4d3c1bad-5d45-4f9d-95f4-b36240acff87)
你好，像这种窗口大小要怎么适配测试视频

**Comment by Keyyy222** [comment]
我是为了使用您文件的非专业人士，请问我一直卡在无匹配到torchvision==0.8.2，我也按照前面说的下载版本，但还是不行，是因为我anaconda没下对还是版本没对，我现在是想完整配置你的环境进行使用，可以的话能给我具体的版本吗
